name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test

      - name: Automatic release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT_TOKEN }}"
          prerelease: false

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
